### ISSUE TITLE
Figure out how to properly sort RPM revisions

### ISSUE THREAD

**Issue by PerilousApricot** [accre/lstore#27]
With the following repo:

```
centos/7/packages/accre-gridftp-0.3.0-1.x86_64.rpm
centos/7/packages/accre-gridftp-0.3.0-22-g28bc94b025e55fc39e87d7c55bc2a723-dev-1.x86_64.rpm
centos/7/packages/accre-gridftp-0.3.0-29-ga36bd793f06ee30785901aea6f981a31-dev-1.x86_64.rpm
centos/7/packages/accre-gridftp-0.3.0-8-g9294ae15d86be993055d090b0458ea12-1.x86_64.rpm
centos/7/packages/accre-gridftp-0.4.0-rc2-1-g0cc8ca0a958919a8a2104691be920999-1.x86_64.rpm
```

`yum install accre-gridftp` says:

```
Package accre-gridftp-0.3.0_2_g74e4cb7196437648c983a7d580edd83e-1.x86_64 already installed and latest version
```

This is wrong.

**Comment by PerilousApricot** [comment]
So, I'm not sure if this is the expected behavior, but I had to `yum clean all` to get it to see the different packages. Doing different combinations of `yum update` didn't seem to pull in the new metadata.

**Comment by skj-dev** [comment]
Yum caches metadata for six hours by default. It can be adjusted with the metadata_expire configuration option.

http://linux.die.net/man/5/yum.conf

**metadata_expire** Time (in seconds) after which the metadata will expire. So that if the current metadata downloaded is less than this many seconds old then yum will not update the metadata against the repository. If you find that yum is not downloading information on updates as often as you would like lower the value of this option. You can also change from the default of using seconds to using days, hours or minutes by appending a d, h or m respectively. The default is 6 hours, to compliment yum-updatesd running once an hour. It's also possible to use the word "never", meaning that the metadata will never expire. Note that when using a metalink file the metalink must always be newer than the metadata for the repository, due to the validation, so this timeout also applies to the metalink file.

**Comment by PerilousApricot** [comment]
:sparkling_heart: - I'll make sure to crank this for our testing repositories. Thanks!

**Comment by hellermf** [comment]
That is great, up until now I was doing a "touch /etc/yum.repos.d/lstore.repo" before installing packages as a work around to this issue.

**Comment by PerilousApricot** [comment]
Wanna make a PR to change the config? Does debian have an analogue?

**Comment by skj-dev** [comment]
> Wanna make a PR to change the config? 

How will a PR help you in this context? The setting is client side.

**Comment by PerilousApricot** [comment]
I was talking to @hellermf, but we make an lstore-release RPM that installs the yum repo list. We can add the config value there (aka here https://github.com/accre/lstore-release/blob/master/source/release/rpm-release/lstore.repo) which will override the global option.

**Comment by skj-dev** [comment]
Ahhh, sorry. That makes sense. #scatterbrained

**Comment by hellermf** [comment]
apt-get update doesn't have this problem, it always checks the repos for changes.
--Matt

----- Original Message -----
